/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_nateschieber_groovesprings_audio_jni_JniMain */

#ifndef _Included_dev_nateschieber_groovesprings_audio_jni_JniMain
#define _Included_dev_nateschieber_groovesprings_audio_jni_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_nateschieber_groovesprings_audio_jni_JniMain
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_nateschieber_groovesprings_audio_jni_JniMain_helloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
