/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_nateschieber_groovesprings_jni_JniMain */

#ifndef _Included_dev_nateschieber_groovesprings_jni_JniMain
#define _Included_dev_nateschieber_groovesprings_jni_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    addNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_addNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    initPlaybackLoopNative
 * Signature: (JLjava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_initPlaybackLoopNative
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong);

/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    readSfInfoNative
 * Signature: (Ljava/lang/String;)Ldev/nateschieber/groovesprings/jni/SfInfo;
 */
JNIEXPORT jobject JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_readSfInfoNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    allocVst3HostNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_allocVst3HostNative
  (JNIEnv *, jobject);

/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    deleteVst3HostNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_deleteVst3HostNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    initVst3HostNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_initVst3HostNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
