/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_nateschieber_groovesprings_jni_JniMain */

#ifndef _Included_dev_nateschieber_groovesprings_jni_JniMain
#define _Included_dev_nateschieber_groovesprings_jni_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    addNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_addNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dev_nateschieber_groovesprings_jni_JniMain
 * Method:    initPlaybackLoopNative
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_nateschieber_groovesprings_jni_JniMain_initPlaybackLoopNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
